### ISSUE TITLE
Cannot run project using virtualenv

### ISSUE THREAD

**Issue by mushketyk** [levlaz/braindump#145]
I followed steps in the README, but when I tried to install all the requirements I've stumbled on the following error:

(env)(master) % pip install -r requirements.txt
Collecting Babel==2.1.1 (from -r requirements.txt (line 1))
/home/proger/Development/braindump/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  **Could not find a version that satisfies the requirement Babel==2.1.1 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for Babel==2.1.1 (from -r requirements.txt (line 1))**

How can I fix this?

**Comment by levlaz** [comment]
@mushketyk I have been doing `pip freeze > requirements.txt` but this pulls in all submodules as well, I think it would be better if I just defined which modules I *really* need so that if there are updates to the submodule version they will not break like this. 

In the meantime, can you try to remove the Babel version from requirements.txt to see if that helps?

**Comment by levlaz** [comment]
I cleaned up the requirements.txt to only include the things that are actually required. This should work now!
