### ISSUE TITLE
sidebar is not fixed

### ISSUE THREAD

**Issue by Fahreeve** [levlaz/braindump#154]
![2016-01-03 14 35 29](https://cloud.githubusercontent.com/assets/3227524/12078552/a9865d66-b227-11e5-8eb0-f2d776e72ca6.png)
whan I can see django message after changing notes

**Comment by levlaz** [comment]
@Fahreeve Not sure what you mean by "django message", we are using Flask.

**Comment by Fahreeve** [comment]
@levlaz I mean orange box with message in the header of the page

**Comment by levlaz** [comment]
Sorry, I am still not understanding your question. :(

**Comment by Fahreeve** [comment]
sory, my english is bad(

1) I created new note
2) I updated this note and I see this message
![2016-01-04 21 12 05](https://cloud.githubusercontent.com/assets/3227524/12096667/0276e03e-b328-11e5-939a-f9524d5928d2.png)
"The note has been updated" without indentation
3) I scrolled down the page and see this
![2016-01-04 21 12 12](https://cloud.githubusercontent.com/assets/3227524/12096771/c06bfcb4-b328-11e5-850e-e4baa63c8108.png)
see lower left corner

**Comment by levlaz** [comment]
No problem at all, you can ask in Russian too, Я говорю по русски ;) 

This makes perfect sense. 

Yes I am aware that this is broken. The flashing message should be a popover instead of pushing everything down. This was broken after the third iteration of the UI came out. I am mostly happy with the way things look now so this is something that needs to be fixed with the current state.
